"""add deleted_at to image generations

Revision ID: 9cd5c2e8e569
Revises: ed66d3ff03d6
Create Date: 2026-10-02 09:54:23.203920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd5c2e8e569'
down_revision: Union[str, Sequence[str], None] = 'ed66d3ff03d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_generations', 'deleted_at')
    # ### end Alembic commands ###
