"""create image generations table

Revision ID: ed66d3ff03d6
Revises: 
Create Date: 2026-09-29 09:28:18.446619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed66d3ff03d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('image_analysis', sa.Text(), nullable=True),
    sa.Column('final_prompt', sa.Text(), nullable=False),
    sa.Column('generation_type', sa.String(length=32), nullable=False),
    sa.Column('input_object_key', sa.String(length=1024), nullable=True),
    sa.Column('output_object_key', sa.String(length=1024), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_generations_created_at'), 'image_generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_image_generations_generation_type'), 'image_generations', ['generation_type'], unique=False)
    op.create_index(op.f('ix_image_generations_status'), 'image_generations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_generations_status'), table_name='image_generations')
    op.drop_index(op.f('ix_image_generations_generation_type'), table_name='image_generations')
    op.drop_index(op.f('ix_image_generations_created_at'), table_name='image_generations')
    op.drop_table('image_generations')
    # ### end Alembic commands ###
